// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** ตัดช่องว่าง เครื่องหมายคำพูด และ BOM ที่อาจติดมาจากไฟล์ .env
 *  BOM (\uFEFF) เกิดขึ้นบ่อยเมื่อสร้างไฟล์ .env บน Windows ด้วย PowerShell
 *  ถ้าไม่ตัดออก จะทำให้ new Headers() ล้มเหลวด้วยข้อความ
 *  "String contains non ISO-8859-1 code point" ซึ่งหาสาเหตุยากมาก
 */
const cleanEnv = (v: string | undefined): string =>
  (v ?? '').replace(/^\uFEFF/, '').trim().replace(/^["']|["']$/g, '');

const SUPABASE_URL = cleanEnv(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = cleanEnv(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'ไม่พบค่าเชื่อมต่อฐานข้อมูล — ตรวจสอบไฟล์ .env ว่ามี VITE_SUPABASE_URL ' +
    'และ VITE_SUPABASE_PUBLISHABLE_KEY ครบถ้วน แล้วรัน npm run dev ใหม่',
  );
}


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
